#
# board/renesas/ulcb/Makefile
#
# Copyright (C) 2016 Renesas Electronics Corporation
# Copyright (C) 2016 Cogent Embedded, Inc.
#
# SPDX-License-Identifier: GPL-2.0+
#

obj-y	:= ulcb.o ../rcar-gen3-common/common.o
